on:
  push:
    paths:
      - "version"
      - "entrypoint.sh"
      - "Dockerfile"
      - ".github/workflows/build-push.yaml"

name: docker build push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up env
        run: |
          echo "$(cat version | head -n2)" >> $GITHUB_ENV
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker buildx build --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/s390x,linux/ppc64le \
          --output "type=image,push=true" \
          --build-arg HatH_VERSION=${{ env.HatH_VERSION }} \
          --build-arg HatH_CHECKSUM=${{ env.HatH_CHECKSUM }} \
          --tag "${{ secrets.DOCKERHUB_USERNAME }}/hath:latest" \
          --tag "${{ secrets.DOCKERHUB_USERNAME }}/hath:${{ env.HatH_VERSION }}" \
          --file Dockerfile .

